=== psemek/Tworzenie-uslug-sieciowych/lab04/plyty.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="plyty">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="plyta" maxOccurs="unbounded">
          <xsd:complexType>
            <xsd:all>
              <xsd:element name="wykonawca" type="xsd:string" minOccurs="0"></xsd:element>
              <xsd:element name="tytul" minOccurs="0"></xsd:element>
              <xsd:element name="czas_trwania" minOccurs="0"></xsd:element>
              <xsd:element name="numer_katalogowy" minOccurs="0">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="\d{9}">
                    </xsd:pattern>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:element>
              <xsd:element name="cena" minOccurs="0" type="xsd:int">
              </xsd:element>
            </xsd:all>
            <xsd:attribute name="typ" use="required">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:enumeration value="DVD"></xsd:enumeration>
                  <xsd:enumeration value="CD"></xsd:enumeration>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:attribute>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>
</xsd:schema>

=== psemek/Tworzenie-uslug-sieciowych/lab04/plyty2.xml
<?xml version="1.0" encoding="utf-8"?>
<plyty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="plyty.xsd">
<plyta typ="CD">
  <wykonawca>Placebo</wykonawca>
  <tytul>Black Market Music</tytul>
  <czas_trwania>53</czas_trwania>
</plyta >
<plyta typ="DVD">
  <numer_katalogowy>00232</numer_katalogowy>
  <cena>122</cena>
</plyta>
<plyta typ="CD">
  <wykonawca>The Doors</wykonawca>
  <tytul>Morrison Hotel</tytul>
</plyta>
<plyta typ="CD">
  <wykonawca>The Killers</wykonawca>
  <tytul>Hot Fuss</tytul>
</plyta>
<plyta typ="DVD">
  <numer_katalogowy>00452</numer_katalogowy>
  <cena>63</cena>
</plyta>
<plyta typ="CD">
  <numer_katalogowy>00505</numer_katalogowy>
  <cena>45</cena>
</plyta>
</plyty>
